
name: SiteWasm CustomDomain

# Run workflow on every push to the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy-to-github-pages:
  # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the main branch
    - uses: actions/checkout@v3
    # sets up .NET Core SDK 6.0.x
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    # Install dotnet wasm buildtools workload
    - name: Install .NET WASM Build Tools
      run: dotnet workload install wasm-tools
    # Install necessary npm package
    - name: Install npm pacakage dependencies
      run: npm install
      working-directory: NpmJS 
    # Publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish SiteWasm.csproj -c:Release -o dist/SiteWasm --nologo
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages-alternative
        FOLDER: dist/SiteWasm/wwwroot      
